package channel

import (
	"context"
	"errors"
	"fmt"
	"io"
	"net"
	"net/http"
	"regexp"
	"strings"
	"sync"
	"time"

	common2 "github.com/QuantumNous/new-api/common"
	"github.com/QuantumNous/new-api/logger"
	"github.com/QuantumNous/new-api/relay/common"
	"github.com/QuantumNous/new-api/relay/constant"
	"github.com/QuantumNous/new-api/relay/helper"
	"github.com/QuantumNous/new-api/service"
	"github.com/QuantumNous/new-api/setting/operation_setting"
	"github.com/QuantumNous/new-api/types"

	"github.com/bytedance/gopkg/util/gopool"
	"github.com/gin-gonic/gin"
	"github.com/gorilla/websocket"
	"golang.org/x/net/http/httpguts"
)

// applyUpstreamContentLength populates req.ContentLength when the upstream
// body is wrapped in a BodyStorage (see relay/common/outbound_body.go).
//
// net/http.NewRequest only auto-detects ContentLength for *bytes.Reader,
// *bytes.Buffer and *strings.Reader. When the body is a type-erased io.Reader
// (which is the case for ReaderOnly(BodyStorage)), the Content-Length header
// would otherwise be omitted, forcing chunked transfer encoding and breaking
// some upstreams that require an explicit Content-Length.
func applyUpstreamContentLength(req *http.Request, info *common.RelayInfo) {
	if info == nil {
		return
	}
	if info.UpstreamRequestBodySize > 0 && req.ContentLength <= 0 {
		req.ContentLength = info.UpstreamRequestBodySize
	}
}

func SetupApiRequestHeader(info *common.RelayInfo, c *gin.Context, req *http.Header) {
	if info.RelayMode == constant.RelayModeAudioTranscription || info.RelayMode == constant.RelayModeAudioTranslation {
		// multipart/form-data
	} else if info.RelayMode == constant.RelayModeRealtime {
		// websocket
	} else {
		req.Set("Content-Type", c.Request.Header.Get("Content-Type"))
		req.Set("Accept", c.Request.Header.Get("Accept"))
		if info.IsStream && c.Request.Header.Get("Accept") == "" {
			req.Set("Accept", "text/event-stream")
		}
	}
}

const clientHeaderPlaceholderPrefix = "{client_header:"

const (
	headerPassthroughAllKey        = "*"
	headerPassthroughRegexPrefix   = "re:"
	headerPassthroughRegexPrefixV2 = "regex:"
)

var passthroughSkipHeaderNamesLower = map[string]struct{}{
	// RFC 7230 hop-by-hop headers.
	"connection":          {},
	"keep-alive":          {},
	"proxy-authenticate":  {},
	"proxy-authorization": {},
	"te":                  {},
	"trailer":             {},
	"transfer-encoding":   {},
	"upgrade":             {},

	"cookie": {},

	// Additional headers that should not be forwarded by name-matching passthrough rules.
	"host":            {},
	"content-length":  {},
	"accept-encoding": {},

	// Do not passthrough credentials by wildcard/regex.
	"authorization":  {},
	"x-api-key":      {},
	"x-goog-api-key": {},

	// WebSocket handshake headers are generated by the client/dialer.
	"sec-websocket-key":        {},
	"sec-websocket-version":    {},
	"sec-websocket-extensions": {},
}

var headerPassthroughRegexCache sync.Map // map[string]*regexp.Regexp

func getHeaderPassthroughRegex(pattern string) (*regexp.Regexp, error) {
	pattern = strings.TrimSpace(pattern)
	if pattern == "" {
		return nil, errors.New("empty regex pattern")
	}
	if v, ok := headerPassthroughRegexCache.Load(pattern); ok {
		if re, ok := v.(*regexp.Regexp); ok {
			return re, nil
		}
		headerPassthroughRegexCache.Delete(pattern)
	}
	compiled, err := regexp.Compile(pattern)
	if err != nil {
		return nil, err
	}
	actual, _ := headerPassthroughRegexCache.LoadOrStore(pattern, compiled)
	if re, ok := actual.(*regexp.Regexp); ok {
		return re, nil
	}
	return compiled, nil
}

func IsHeaderPassthroughRuleKey(key string) bool {
	return isHeaderPassthroughRuleKey(key)
}
func isHeaderPassthroughRuleKey(key string) bool {
	key = strings.TrimSpace(key)
	if key == "" {
		return false
	}
	if key == headerPassthroughAllKey {
		return true
	}
	lower := strings.ToLower(key)
	return strings.HasPrefix(lower, headerPassthroughRegexPrefix) || strings.HasPrefix(lower, headerPassthroughRegexPrefixV2)
}

func shouldSkipPassthroughHeader(name string) bool {
	name = strings.TrimSpace(name)
	if name == "" {
		return true
	}
	lower := strings.ToLower(name)
	if _, ok := passthroughSkipHeaderNamesLower[lower]; ok {
		return true
	}
	return false
}

func applyHeaderOverridePlaceholders(template string, c *gin.Context, apiKey string) (string, bool, error) {
	trimmed := strings.TrimSpace(template)
	if strings.HasPrefix(trimmed, clientHeaderPlaceholderPrefix) {
		afterPrefix := trimmed[len(clientHeaderPlaceholderPrefix):]
		end := strings.Index(afterPrefix, "}")
		if end < 0 || end != len(afterPrefix)-1 {
			return "", false, fmt.Errorf("client_header placeholder must be the full value: %q", template)
		}

		name := strings.TrimSpace(afterPrefix[:end])
		if name == "" {
			return "", false, fmt.Errorf("client_header placeholder name is empty: %q", template)
		}
		if c == nil || c.Request == nil {
			return "", false, fmt.Errorf("missing request context for client_header placeholder")
		}
		clientHeaderValue := c.Request.Header.Get(name)
		if strings.TrimSpace(clientHeaderValue) == "" {
			return "", false, nil
		}
		// Do not interpolate {api_key} inside client-supplied content.
		return clientHeaderValue, true, nil
	}

	if strings.Contains(template, "{api_key}") {
		template = strings.ReplaceAll(template, "{api_key}", apiKey)
	}
	if strings.TrimSpace(template) == "" {
		return "", false, nil
	}
	return template, true, nil
}

// processHeaderOverride applies channel header overrides, with placeholder substitution.
// Supported placeholders:
//   - {api_key}: resolved to the channel API key
//   - {client_header:<name>}: resolved to the incoming request header value
//
// Header passthrough rules (keys only; values are ignored):
//   - "*": passthrough all incoming headers by name (excluding unsafe headers)
//   - "re:<regex>" / "regex:<regex>": passthrough headers whose names match the regex (Go regexp)
//
// Passthrough rules are applied first, then normal overrides are applied, so explicit overrides win.
func processHeaderOverride(info *common.RelayInfo, c *gin.Context) (map[string]string, error) {
	headerOverride := make(map[string]string)
	if info == nil {
		return headerOverride, nil
	}

	headerOverrideSource := common.GetEffectiveHeaderOverride(info)

	passAll := false
	var passthroughRegex []*regexp.Regexp
	if !info.IsChannelTest {
		for k := range headerOverrideSource {
			key := strings.TrimSpace(strings.ToLower(k))
			if key == "" {
				continue
			}
			if key == headerPassthroughAllKey {
				passAll = true
				continue
			}

			var pattern string
			switch {
			case strings.HasPrefix(key, headerPassthroughRegexPrefix):
				pattern = strings.TrimSpace(key[len(headerPassthroughRegexPrefix):])
			case strings.HasPrefix(key, headerPassthroughRegexPrefixV2):
				pattern = strings.TrimSpace(key[len(headerPassthroughRegexPrefixV2):])
			default:
				continue
			}

			if pattern == "" {
				return nil, types.NewError(fmt.Errorf("header passthrough regex pattern is empty: %q", k), types.ErrorCodeChannelHeaderOverrideInvalid)
			}
			compiled, err := getHeaderPassthroughRegex(pattern)
			if err != nil {
				return nil, types.NewError(err, types.ErrorCodeChannelHeaderOverrideInvalid)
			}
			passthroughRegex = append(passthroughRegex, compiled)
		}
	}

	if passAll || len(passthroughRegex) > 0 {
		if c == nil || c.Request == nil {
			return nil, types.NewError(fmt.Errorf("missing request context for header passthrough"), types.ErrorCodeChannelHeaderOverrideInvalid)
		}
		for name := range c.Request.Header {
			if shouldSkipPassthroughHeader(name) {
				continue
			}
			if !passAll {
				matched := false
				for _, re := range passthroughRegex {
					if re.MatchString(name) {
						matched = true
						break
					}
				}
				if !matched {
					continue
				}
			}
			value := strings.TrimSpace(c.Request.Header.Get(name))
			if value == "" {
				continue
			}
			headerOverride[strings.ToLower(strings.TrimSpace(name))] = value
		}
	}

	for k, v := range headerOverrideSource {
		if isHeaderPassthroughRuleKey(k) {
			continue
		}
		key := strings.TrimSpace(strings.ToLower(k))
		if key == "" {
			continue
		}

		str, ok := v.(string)
		if !ok {
			return nil, types.NewError(nil, types.ErrorCodeChannelHeaderOverrideInvalid)
		}
		if info.IsChannelTest && strings.HasPrefix(strings.TrimSpace(str), clientHeaderPlaceholderPrefix) {
			continue
		}

		value, include, err := applyHeaderOverridePlaceholders(str, c, info.ApiKey)
		if err != nil {
			return nil, types.NewError(err, types.ErrorCodeChannelHeaderOverrideInvalid)
		}
		if !include {
			continue
		}

		headerOverride[key] = value
	}
	return headerOverride, nil
}

func ResolveHeaderOverride(info *common.RelayInfo, c *gin.Context) (map[string]string, error) {
	return processHeaderOverride(info, c)
}

func applyHeaderOverrideToRequest(req *http.Request, headerOverride map[string]string) {
	if req == nil {
		return
	}
	for key, value := range headerOverride {
		req.Header.Set(key, value)
		// set Host in req
		if strings.EqualFold(key, "Host") {
			req.Host = value
		}
	}
}

func DoApiRequest(a Adaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*http.Response, error) {
	if c == nil || c.Request == nil {
		return nil, errors.New("upstream request context is unavailable")
	}
	fullRequestURL, err := a.GetRequestURL(info)
	if err != nil {
		return nil, fmt.Errorf("get request url failed: %w", err)
	}
	logger.LogDebug(c, "upstream request URL: %s", common2.SanitizeErrorMessage(fullRequestURL))
	req, err := http.NewRequestWithContext(c.Request.Context(), c.Request.Method, fullRequestURL, requestBody)
	if err != nil {
		return nil, fmt.Errorf("new request failed: %w", err)
	}
	applyUpstreamContentLength(req, info)
	headers := req.Header
	err = a.SetupRequestHeader(c, &headers, info)
	if err != nil {
		return nil, fmt.Errorf("setup request header failed: %w", err)
	}
	// 在 SetupRequestHeader 之后应用 Header Override，确保用户设置优先级最高
	// 这样可以覆盖默认的 Authorization header 设置
	headerOverride, err := processHeaderOverride(info, c)
	if err != nil {
		return nil, err
	}
	applyHeaderOverrideToRequest(req, headerOverride)
	resp, err := doRequest(c, req, info)
	if err != nil {
		return nil, fmt.Errorf("do request failed: %w", err)
	}
	return resp, nil
}

func DoFormRequest(a Adaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*http.Response, error) {
	if c == nil || c.Request == nil {
		return nil, errors.New("upstream request context is unavailable")
	}
	fullRequestURL, err := a.GetRequestURL(info)
	if err != nil {
		return nil, fmt.Errorf("get request url failed: %w", err)
	}
	logger.LogDebug(c, "upstream request URL: %s", common2.SanitizeErrorMessage(fullRequestURL))
	req, err := http.NewRequestWithContext(c.Request.Context(), c.Request.Method, fullRequestURL, requestBody)
	if err != nil {
		return nil, fmt.Errorf("new request failed: %w", err)
	}
	applyUpstreamContentLength(req, info)
	// set form data
	req.Header.Set("Content-Type", c.Request.Header.Get("Content-Type"))
	headers := req.Header
	err = a.SetupRequestHeader(c, &headers, info)
	if err != nil {
		return nil, fmt.Errorf("setup request header failed: %w", err)
	}
	// 在 SetupRequestHeader 之后应用 Header Override，确保用户设置优先级最高
	// 这样可以覆盖默认的 Authorization header 设置
	headerOverride, err := processHeaderOverride(info, c)
	if err != nil {
		return nil, err
	}
	applyHeaderOverrideToRequest(req, headerOverride)
	resp, err := doRequest(c, req, info)
	if err != nil {
		return nil, fmt.Errorf("do request failed: %w", err)
	}
	return resp, nil
}

func DoWssRequest(a Adaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*websocket.Conn, error) {
	if c == nil || c.Request == nil {
		return nil, errors.New("upstream request context is unavailable")
	}
	fullRequestURL, err := a.GetRequestURL(info)
	if err != nil {
		return nil, fmt.Errorf("get request url failed: %w", err)
	}
	targetHeader := http.Header{}
	err = a.SetupRequestHeader(c, &targetHeader, info)
	if err != nil {
		return nil, fmt.Errorf("setup request header failed: %w", err)
	}
	// 在 SetupRequestHeader 之后应用 Header Override，确保用户设置优先级最高
	// 这样可以覆盖默认的 Authorization header 设置
	headerOverride, err := processHeaderOverride(info, c)
	if err != nil {
		return nil, err
	}
	for key, value := range headerOverride {
		targetHeader.Set(key, value)
	}
	targetHeader.Set("Content-Type", c.Request.Header.Get("Content-Type"))

	dialCtx := c.Request.Context()
	firstByteTimeout := helper.FirstByteFailoverTimeout(info)
	var cancelFirstByte context.CancelFunc
	if firstByteTimeout > 0 {
		dialCtx, cancelFirstByte = context.WithTimeout(dialCtx, firstByteTimeout)
	}
	if cancelFirstByte != nil {
		defer cancelFirstByte()
	}

	dialer := *websocket.DefaultDialer
	if err := common.MarkRoutingUpstreamSent(c); err != nil {
		return nil, fmt.Errorf("mark routing upstream sent: %w", err)
	}
	targetConn, handshakeResponse, err := dialer.DialContext(dialCtx, fullRequestURL, targetHeader)
	if err != nil {
		if firstByteTimeout > 0 && firstByteDeadlineExceeded(dialCtx, err) {
			if info.StreamStatus == nil {
				info.StreamStatus = common.NewStreamStatus()
			}
			info.StreamStatus.SetEndReason(common.StreamEndReasonFirstByteTimeout, err)
		}
		return nil, common.NewWebSocketHandshakeError(handshakeResponse, err)
	}
	// send request body
	//all, err := io.ReadAll(requestBody)
	//err = service.WssString(c, targetConn, string(all))
	return targetConn, nil
}

func firstByteDeadlineExceeded(ctx context.Context, err error) bool {
	if ctx != nil && errors.Is(ctx.Err(), context.DeadlineExceeded) {
		return true
	}
	if errors.Is(err, context.DeadlineExceeded) {
		return true
	}
	var netErr net.Error
	return errors.As(err, &netErr) && netErr.Timeout()
}

func startPingKeepAlive(c *gin.Context, info *common.RelayInfo, pingInterval time.Duration, cancelAttempt context.CancelFunc) (context.CancelFunc, <-chan struct{}, <-chan error) {
	pingerCtx, stopPinger := context.WithCancel(context.Background())
	done := make(chan struct{})
	errChan := make(chan error, 1)

	gopool.Go(func() {
		defer close(done)
		defer func() {
			if r := recover(); r != nil {
				panicErr := fmt.Errorf("SSE ping goroutine panic: %v", r)
				logger.LogError(c, panicErr.Error())
				if info.StreamStatus == nil {
					info.StreamStatus = common.NewStreamStatus()
				}
				info.StreamStatus.RecordError(panicErr.Error())
				info.StreamStatus.SetEndReason(common.StreamEndReasonPanic, panicErr)
				errChan <- panicErr
				if cancelAttempt != nil {
					cancelAttempt()
				}
			}
			logger.LogDebug(c, "SSE ping goroutine stopped")
		}()

		if pingInterval <= 0 {
			pingInterval = helper.DefaultPingInterval
		}

		ticker := time.NewTicker(pingInterval)
		// 确保在任何情况下都清理ticker
		defer func() {
			ticker.Stop()
			logger.LogDebug(c, "SSE ping ticker stopped")
		}()

		var pingMutex sync.Mutex
		logger.LogDebug(c, "SSE ping goroutine started")

		// 增加超时控制，防止goroutine长时间运行
		maxPingDuration := 120 * time.Minute // 最大ping持续时间
		pingTimeout := time.NewTimer(maxPingDuration)
		defer pingTimeout.Stop()

		for {
			select {
			// 发送 ping 数据
			case <-ticker.C:
				if err := sendPingData(c, &pingMutex); err != nil {
					logger.LogDebug(c, "SSE ping error, stopping goroutine: %s", err.Error())
					if info.StreamStatus == nil {
						info.StreamStatus = common.NewStreamStatus()
					}
					info.StreamStatus.RecordError(err.Error())
					info.StreamStatus.SetEndReason(common.StreamEndReasonPingFail, err)
					errChan <- err
					if cancelAttempt != nil {
						cancelAttempt()
					}
					return
				}
			// 收到退出信号
			case <-pingerCtx.Done():
				return
			// request 结束
			case <-c.Request.Context().Done():
				return
			// 超时保护，防止goroutine无限运行
			case <-pingTimeout.C:
				logger.LogDebug(c, "SSE ping goroutine timeout, stopping")
				return
			}
		}
	})

	return stopPinger, done, errChan
}

func sendPingData(c *gin.Context, mutex *sync.Mutex) error {
	mutex.Lock()
	defer mutex.Unlock()

	// Bound the write so a slow client cannot block this goroutine forever;
	// doRequest's defer waits for the pinger to exit before returning.
	helper.ExtendWriteDeadline(c)
	err := helper.PingData(c)
	if err != nil {
		logger.LogError(c, "SSE ping error: "+err.Error())
		return err
	}

	logger.LogDebug(c, "SSE ping data sent")
	return nil
}

type upstreamFirstByteGuard struct {
	once   sync.Once
	timer  *time.Timer
	cancel context.CancelCauseFunc
	status *common.StreamStatus
	seen   bool
}

func newUpstreamFirstByteGuard(
	timeout time.Duration,
	cancel context.CancelCauseFunc,
	status *common.StreamStatus,
) *upstreamFirstByteGuard {
	guard := &upstreamFirstByteGuard{cancel: cancel, status: status}
	guard.timer = time.AfterFunc(timeout, func() {
		guard.once.Do(func() {
			guard.status.SetEndReason(common.StreamEndReasonFirstByteTimeout, context.DeadlineExceeded)
			guard.cancel(context.DeadlineExceeded)
		})
	})
	return guard
}

func (guard *upstreamFirstByteGuard) observeFirstByte() bool {
	if guard == nil {
		return true
	}
	guard.once.Do(func() {
		guard.seen = true
		if guard.timer != nil {
			guard.timer.Stop()
		}
	})
	return guard.seen
}

func (guard *upstreamFirstByteGuard) finishWithoutFirstByte() {
	if guard == nil {
		return
	}
	guard.once.Do(func() {
		if guard.timer != nil {
			guard.timer.Stop()
		}
	})
}

type upstreamAttemptResponseBody struct {
	io.ReadCloser
	firstByte *upstreamFirstByteGuard
	cancel    context.CancelCauseFunc
	// SSE comments, event names, and blank lines are transport noise rather
	// than the first usable model event. The scanner marks a business event.
	businessEventRequired bool
	finish                sync.Once
}

// RoutingFirstByteGuarded lets the stream scanner reuse the transport-level
// deadline instead of starting a second first-byte budget after headers arrive.
func (body *upstreamAttemptResponseBody) RoutingFirstByteGuarded() bool {
	return body != nil && body.firstByte != nil
}

// RoutingMarkFirstByte atomically races the first valid SSE event against the
// absolute transport deadline. False means the timeout already won and the
// caller must not commit the event to the downstream client.
func (body *upstreamAttemptResponseBody) RoutingMarkFirstByte() bool {
	return body == nil || body.firstByte.observeFirstByte()
}

func (body *upstreamAttemptResponseBody) Read(buffer []byte) (int, error) {
	read, err := body.ReadCloser.Read(buffer)
	if read > 0 && !body.businessEventRequired && !body.firstByte.observeFirstByte() {
		return 0, context.DeadlineExceeded
	}
	if err != nil {
		body.finishAttempt()
	}
	return read, err
}

func (body *upstreamAttemptResponseBody) Close() error {
	err := body.ReadCloser.Close()
	body.finishAttempt()
	return err
}

func (body *upstreamAttemptResponseBody) finishAttempt() {
	if body == nil {
		return
	}
	body.finish.Do(func() {
		if body.businessEventRequired {
			body.firstByte.finishWithoutFirstByte()
		} else {
			body.firstByte.observeFirstByte()
		}
		if body.cancel != nil {
			body.cancel(context.Canceled)
		}
	})
}

func DoRequest(c *gin.Context, req *http.Request, info *common.RelayInfo) (*http.Response, error) {
	return doRequest(c, req, info)
}
func doRequest(c *gin.Context, req *http.Request, info *common.RelayInfo) (*http.Response, error) {
	if c == nil || c.Request == nil {
		return nil, errors.New("upstream request context is unavailable")
	}
	if req == nil {
		return nil, errors.New("upstream request is nil")
	}
	if info == nil {
		return nil, errors.New("relay info is nil")
	}
	if info.ChannelMeta == nil {
		return nil, errors.New("relay channel metadata is nil")
	}
	// SetRoutingStrictCapacityReservation and future attempt orchestration may
	// replace the inbound request context after the upstream request was built.
	// Bind at the final send boundary so lease loss, client disconnects, and
	// loser cancellation always reach http.Client.Do.
	req = req.WithContext(c.Request.Context())

	var client *http.Client
	var err error
	if info.ChannelSetting.Proxy != "" {
		client, err = service.NewProxyHttpClient(info.ChannelSetting.Proxy)
		if err != nil {
			return nil, fmt.Errorf("new proxy http client failed: %w", err)
		}
	} else {
		client = service.GetHttpClient()
	}

	firstByteTimeout := time.Duration(0)
	if info.IsStream {
		firstByteTimeout = helper.FirstByteFailoverTimeout(info)
	}
	var attemptCancel context.CancelCauseFunc
	var firstByteGuard *upstreamFirstByteGuard
	if firstByteTimeout > 0 {
		reqCtx, cancel := context.WithCancelCause(req.Context())
		attemptCancel = cancel
		req = req.WithContext(reqCtx)
		if info.StreamStatus == nil {
			info.StreamStatus = common.NewStreamStatus()
		}
		firstByteGuard = newUpstreamFirstByteGuard(firstByteTimeout, cancel, info.StreamStatus)
	}

	var stopPinger context.CancelFunc
	var pingerDone <-chan struct{}
	var pingerErr <-chan error
	defer func() {
		if stopPinger != nil {
			stopPinger()
			<-pingerDone
			logger.LogDebug(c, "SSE ping goroutine stopped by defer")
		}
		if firstByteGuard != nil {
			firstByteGuard.observeFirstByte()
		}
		if attemptCancel != nil {
			attemptCancel(context.Canceled)
		}
	}()
	if info.IsStream {
		helper.SetEventStreamHeaders(c)
		// 处理流式请求的 ping 保活
		generalSettings := operation_setting.GetGeneralSetting()
		if generalSettings.PingIntervalEnabled && !info.DisablePing && shouldStartPreResponseStreamPing(info) {
			pingInterval := time.Duration(generalSettings.PingIntervalSeconds) * time.Second
			if attemptCancel == nil {
				attemptCtx, cancel := context.WithCancelCause(req.Context())
				attemptCancel = cancel
				req = req.WithContext(attemptCtx)
			}
			stopPinger, pingerDone, pingerErr = startPingKeepAlive(c, info, pingInterval, func() {
				attemptCancel(errors.New("pre-response stream ping failed"))
			})
		}
	}

	if err := common.MarkRoutingUpstreamSent(c); err != nil {
		return nil, fmt.Errorf("mark routing upstream sent: %w", err)
	}
	resp, err := client.Do(req)
	if stopPinger != nil {
		stopPinger()
		<-pingerDone
		stopPinger = nil
	}
	if pingerErr != nil {
		select {
		case err := <-pingerErr:
			if resp != nil && resp.Body != nil {
				service.CloseResponseBodyGracefully(resp)
			}
			return nil, types.NewError(err, types.ErrorCodeBadResponse)
		default:
		}
	}
	if err != nil {
		logger.LogError(c, "do request failed: "+err.Error())
		if firstByteTimeout > 0 && errors.Is(context.Cause(req.Context()), context.DeadlineExceeded) {
			if info.StreamStatus == nil {
				info.StreamStatus = common.NewStreamStatus()
			}
			info.StreamStatus.SetEndReason(common.StreamEndReasonFirstByteTimeout, err)
			return nil, types.NewErrorWithStatusCode(err, types.ErrorCodeDoRequestFailed, http.StatusGatewayTimeout, types.ErrOptionWithHideErrMsg("upstream error: first byte timeout"))
		}
		return nil, types.NewError(err, types.ErrorCodeDoRequestFailed, types.ErrOptionWithHideErrMsg("upstream error: do request failed"))
	}
	if resp == nil {
		return nil, errors.New("resp is nil")
	}
	if attemptCancel != nil && resp.Body != nil {
		businessEventRequired := strings.HasPrefix(strings.ToLower(resp.Header.Get("Content-Type")), "text/event-stream")
		if !businessEventRequired && (resp.Body == http.NoBody || resp.ContentLength == 0) {
			firstByteGuard.observeFirstByte()
		}
		resp.Body = &upstreamAttemptResponseBody{
			ReadCloser:            resp.Body,
			firstByte:             firstByteGuard,
			cancel:                attemptCancel,
			businessEventRequired: businessEventRequired,
		}
		firstByteGuard = nil
		attemptCancel = nil
	}

	if upID := resp.Header.Get(common2.RequestIdKey); upID != "" {
		c.Set(common2.UpstreamRequestIdKey, upID)
	}

	if req.Body != nil {
		_ = req.Body.Close()
	}
	if c.Request.Body != nil {
		_ = c.Request.Body.Close()
	}
	return resp, nil
}

func shouldStartPreResponseStreamPing(info *common.RelayInfo) bool {
	if info == nil || !info.IsStream {
		return false
	}
	return helper.FirstByteFailoverTimeout(info) == 0
}

func DoTaskApiRequest(a TaskAdaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*http.Response, error) {
	if c == nil || c.Request == nil {
		return nil, errors.New("upstream request context is unavailable")
	}
	fullRequestURL, err := a.BuildRequestURL(info)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequestWithContext(c.Request.Context(), c.Request.Method, fullRequestURL, requestBody)
	if err != nil {
		return nil, fmt.Errorf("new request failed: %w", err)
	}
	applyUpstreamContentLength(req, info)
	req.GetBody = func() (io.ReadCloser, error) {
		return io.NopCloser(requestBody), nil
	}

	err = a.BuildRequestHeader(c, req, info)
	if err != nil {
		return nil, fmt.Errorf("setup request header failed: %w", err)
	}
	for name, values := range req.Header {
		if !httpguts.ValidHeaderFieldName(name) {
			return nil, fmt.Errorf("invalid header field name %q", name)
		}
		for _, value := range values {
			if !httpguts.ValidHeaderFieldValue(value) {
				return nil, fmt.Errorf("invalid header field value for %q", name)
			}
		}
	}
	resp, err := doRequest(c, req, info)
	if err != nil {
		return nil, fmt.Errorf("do request failed: %w", err)
	}
	return resp, nil
}
